const {getPool}=require("./_db");function clean(v){return typeof v==="string"?v.trim():v}
module.exports=async(req,res)=>{if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});try{const b=req.body||{},s1=Number(b.student1_id),s2=b.student2_id===null||b.student2_id===undefined||b.student2_id===""?null:Number(b.student2_id),title=clean(b.project_title),category=clean(b.category),abstractText=clean(b.abstract),functionalities=clean(b.functionalities);
if(!s1||!title||!category||!abstractText||!functionalities)return res.status(400).json({error:"Please fill all required fields."});
if(s2!==null&&s1===s2)return res.status(400).json({error:"Student 1 and Student 2 cannot be the same."});
const pool=getPool();const [r1]=await pool.execute(`SELECT id,enrollment_no,student_name FROM students WHERE id=?`,[s1]);if(!r1.length)return res.status(400).json({error:"Student 1 does not exist."});const student1=r1[0];let student2=null;
if(s2!==null){const [r2]=await pool.execute(`SELECT id,enrollment_no,student_name FROM students WHERE id=?`,[s2]);if(!r2.length)return res.status(400).json({error:"Student 2 does not exist."});student2=r2[0]}
const [e1]=await pool.execute(`SELECT id,group_no FROM projects WHERE student1_id=? OR student2_id=? LIMIT 1`,[s1,s1]);if(e1.length)return res.status(409).json({error:"Student 1 is already registered in another project."});
if(s2!==null){const [e2]=await pool.execute(`SELECT id,group_no FROM projects WHERE student1_id=? OR student2_id=? LIMIT 1`,[s2,s2]);if(e2.length)return res.status(409).json({error:"Student 2 is already registered in another project."})}
const [last]=await pool.query(`SELECT group_no FROM projects ORDER BY id DESC LIMIT 1`);let n=1;if(last.length){const x=parseInt(String(last[0].group_no).replace("G",""),10);if(!isNaN(x))n=x+1}const groupNo="G"+String(n).padStart(3,"0");let result;
if(s2===null){[result]=await pool.execute(`INSERT INTO projects(group_no,student1_id,student1_enrollment_no,student2_id,student2_enrollment_no,project_title,category,abstract,functionalities) VALUES(?,?,?,NULL,NULL,?,?,?,?)`,[groupNo,student1.id,student1.enrollment_no,title,category,abstractText,functionalities])}
else{[result]=await pool.execute(`INSERT INTO projects(group_no,student1_id,student1_enrollment_no,student2_id,student2_enrollment_no,project_title,category,abstract,functionalities) VALUES(?,?,?,?,?,?,?,?,?)`,[groupNo,student1.id,student1.enrollment_no,student2.id,student2.enrollment_no,title,category,abstractText,functionalities])}
return res.status(201).json({success:true,message:"Project registered successfully.",project_id:result.insertId,group_no:groupNo,student1:{enrollment_no:student1.enrollment_no,name:student1.student_name},student2:student2?{enrollment_no:student2.enrollment_no,name:student2.student_name}:null})}catch(err){console.error("PROJECT SUBMISSION ERROR:",err);return res.status(500).json({error:"Database error.",details:err.message})}};
